# Generated by Django 4.0.4 on 2022-05-07 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оценки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.capital', verbose_name='Страна & столица')),
            ],
        ),
    ]
